export const FEATURES_DATA = [
  {
    id: 'ai-analysis',
    iconName: 'Cpu',
    title: 'AI Patent Analysis',
    description: 'Deep neural processing analyzes technical claims against millions of global patent filings in under 30 seconds.',
    accentColor: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'semantic-search',
    iconName: 'Search',
    title: 'Semantic Search',
    description: 'Vector embeddings capture true technical intent beyond exact keyword matches across USPTO, EPO, and WIPO databases.',
    accentColor: 'from-indigo-500 to-purple-600',
  },
  {
    id: 'novelty-detection',
    iconName: 'Sparkles',
    title: 'Novelty Detection',
    description: 'Calculates precision novelty scores by pinpointing prior art overlaps, inventive step gaps, and patentability risks.',
    accentColor: 'from-blue-400 to-cyan-500',
  },
  {
    id: 'similar-finder',
    iconName: 'Layers',
    title: 'Similar Patent Finder',
    description: 'Instantly surfaces top 50 overlapping patents ranked by structural similarity score and claim overlap percentages.',
    accentColor: 'from-emerald-400 to-teal-600',
  },
  {
    id: 'ai-suggestions',
    iconName: 'Lightbulb',
    title: 'AI Suggestions',
    description: 'Actionable automated recommendations to rewrite patent claims, circumvent prior art, and maximize grant probability.',
    accentColor: 'from-amber-400 to-orange-500',
  },
  {
    id: 'pdf-report',
    iconName: 'FileText',
    title: 'PDF Report Generation',
    description: 'Export audit-ready executive reports complete with legal citations, score breakdowns, and visual similarity matrices.',
    accentColor: 'from-rose-500 to-pink-600',
  },
];

export const TIMELINE_STEPS = [
  {
    step: 1,
    title: 'Submit Patent',
    description: 'Upload your patent draft PDF or paste technical claims and abstract into our secure encrypted portal.',
    iconName: 'UploadCloud',
    badgeText: 'Instant Encryption',
  },
  {
    step: 2,
    title: 'AI Processing',
    description: 'Our proprietary transformer model extracts key inventive concepts, dependencies, and claim structures.',
    iconName: 'Zap',
    badgeText: '< 30 Seconds',
  },
  {
    step: 3,
    title: 'Patent Comparison',
    description: 'Cross-references your invention against 140M+ active global patent documents and technical literature.',
    iconName: 'GitCompare',
    badgeText: '140M+ Corpus',
  },
  {
    step: 4,
    title: 'Novelty Report',
    description: 'Receive a comprehensive breakdown with Novelty Score %, prior art mapping, and claim risk alerts.',
    iconName: 'BarChart3',
    badgeText: 'Granular Breakdown',
  },
  {
    step: 5,
    title: 'Download Report',
    description: 'Export publication-ready PDF reports with legal citations for attorneys, investors, or R&D leaders.',
    iconName: 'Download',
    badgeText: 'PDF & JSON Export',
  },
];

export const STATS_DATA = [
  {
    id: 'patents',
    value: 150000,
    prefix: '',
    suffix: '+',
    label: 'Patents Analysed',
    description: 'Cross-referenced against global IP databases',
  },
  {
    id: 'reports',
    value: 45000,
    prefix: '',
    suffix: '+',
    label: 'Reports Generated',
    description: 'Comprehensive prior art & novelty evaluations',
  },
  {
    id: 'score',
    value: 94.2,
    prefix: '',
    suffix: '%',
    label: 'Average Novelty Score',
    description: 'Accuracy correlation with USPTO examiners',
  },
  {
    id: 'users',
    value: 12500,
    prefix: '',
    suffix: '+',
    label: 'Satisfied Users',
    description: 'Patent attorneys, inventors, and enterprise R&D teams',
  },
];

export const TESTIMONIALS_DATA = [
  {
    id: 1,
    name: 'Dr. Elena Rostova',
    role: 'Chief IP Officer, BioTech Innovations',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    quote: 'Patentiq AI reduced our prior art search window from 3 weeks to under 5 minutes. The semantic claim overlap scoring is startlingly precise.',
    rating: 5,
    company: 'BioTech Innovations',
  },
  {
    id: 2,
    name: 'Marcus Vance',
    role: 'Managing Partner, Vance & Partners IP Law',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    quote: 'The PDF reports generated by this tool are client-ready. It surfaces non-obvious prior art citations that standard keyword tools completely miss.',
    rating: 5,
    company: 'Vance Legal Group',
  },
  {
    id: 3,
    name: 'Sarah Chen',
    role: 'VP of Hardware Engineering, Quantum Core',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    quote: 'Before filing our provisional patents, Patentiq AI gives us immediate clarity on claim scope. It has saved us tens of thousands in attorney iteration fees.',
    rating: 5,
    company: 'Quantum Core Technologies',
  },
];

export const FAQ_DATA = [
  {
    id: 'faq-1',
    question: 'How accurate is the AI Patent Novelty Checker?',
    answer: 'Patentiq AI leverages large language models fine-tuned on over 140M global patent filings from USPTO, EPO, WIPO, and JPO. In benchmark tests, our AI claim-comparison algorithm correlates with human examiner prior-art findings with over 94.2% accuracy.',
  },
  {
    id: 'faq-2',
    question: 'Is my patent draft and intellectual property kept secure?',
    answer: 'Absoluty. Security is our highest priority. All patent uploads and technical descriptions are encrypted in transit via TLS 1.3 and at rest via AES-256. Your submissions are never used to train public models or shared with third parties.',
  },
  {
    id: 'faq-3',
    question: 'What file formats can I submit for analysis?',
    answer: 'You can upload patent drafts in PDF, DOCX, or TXT formats, or directly paste abstract sections, independent claims, and dependent claims into our structured input form.',
  },
  {
    id: 'faq-4',
    question: 'How long does it take to generate a complete novelty report?',
    answer: 'A standard comprehensive novelty evaluation takes between 15 and 30 seconds. Detailed PDF report exports with visual similarity heatmaps take an additional 5 seconds.',
  },
  {
    id: 'faq-5',
    question: 'Can I export the novelty report for legal presentation?',
    answer: 'Yes! Reports can be exported as professional audit-ready PDFs, clean Markdown, or structured JSON data. Each report includes timestamped prior art citations, overlap percentages, and claim amendment suggestions.',
  },
  {
    id: 'faq-6',
    question: 'How does semantic search differ from traditional keyword search?',
    answer: 'Keyword search only matches exact words, often missing prior art described using different terminology. Our vector-based semantic search understands technical concepts, functional equivalents, and mathematical relationships across 30+ languages.',
  },
];
