export const INITIAL_DASHBOARD_STATS = [
  {
    id: 'stat-1',
    title: 'Total Patent Analyses',
    value: 128,
    unit: '',
    growth: '+14.2%',
    growthType: 'positive',
    subtitle: '18 added this month',
    iconName: 'FileSearch',
  },
  {
    id: 'stat-2',
    title: 'Average Novelty Score',
    value: 92.4,
    unit: '%',
    growth: '+2.8%',
    growthType: 'positive',
    subtitle: 'Highest in Quantum domain',
    iconName: 'Sparkles',
  },
  {
    id: 'stat-3',
    title: 'Reports Generated',
    value: 94,
    unit: '',
    growth: '+18.5%',
    growthType: 'positive',
    subtitle: 'PDF & JSON exports ready',
    iconName: 'FileText',
  },
  {
    id: 'stat-4',
    title: 'Last Analysis',
    value: '2 hrs ago',
    unit: '',
    growth: 'Completed',
    growthType: 'neutral',
    subtitle: 'US-2026-0098412-A1',
    iconName: 'Clock',
  },
];

export const MONTHLY_NOVELTY_DATA = [
  { month: 'Jan', averageScore: 84.5, totalAnalyses: 12 },
  { month: 'Feb', averageScore: 88.2, totalAnalyses: 16 },
  { month: 'Mar', averageScore: 86.9, totalAnalyses: 14 },
  { month: 'Apr', averageScore: 91.0, totalAnalyses: 22 },
  { month: 'May', averageScore: 89.4, totalAnalyses: 19 },
  { month: 'Jun', averageScore: 94.8, totalAnalyses: 25 },
  { month: 'Jul', averageScore: 92.4, totalAnalyses: 20 },
];

export const TECH_CATEGORIES_DATA = [
  { name: 'Artificial Intelligence & ML', count: 42, percentage: 35, color: '#2563EB' },
  { name: 'Biotechnology & Bio-Sensors', count: 28, percentage: 23, color: '#6366F1' },
  { name: 'Quantum & Optoelectronics', count: 22, percentage: 18, color: '#22C55E' },
  { name: 'Autonomous Robotics', count: 18, percentage: 15, color: '#F59E0B' },
  { name: 'Cybersecurity Protocols', count: 11, percentage: 9, color: '#EF4444' },
];

export const RECENT_ANALYSES_DATA = [
  {
    id: 'pat-001',
    title: 'Quantum Micro-Fluidic Neural Processing Unit',
    patentNumber: 'US-2026-0098412-A1',
    date: '2026-07-25',
    noveltyScore: 94.8,
    status: 'Completed',
    category: 'Quantum Electronics',
    claimsCount: 18,
    priorArtMatches: 3,
  },
  {
    id: 'pat-002',
    title: 'Autonomous UAV Swarm Collision Avoidance Mesh',
    patentNumber: 'US-2026-0084719-A1',
    date: '2026-07-24',
    noveltyScore: 88.2,
    status: 'Completed',
    category: 'Autonomous Robotics',
    claimsCount: 14,
    priorArtMatches: 7,
  },
  {
    id: 'pat-003',
    title: 'Biocompatible Graphene Glucose Sensor Array',
    patentNumber: 'EP-3940192-B1',
    date: '2026-07-22',
    noveltyScore: 96.1,
    status: 'Completed',
    category: 'Biotechnology',
    claimsCount: 22,
    priorArtMatches: 1,
  },
  {
    id: 'pat-004',
    title: 'Zero-Knowledge Cryptographic Key Exchange for Edge IoT',
    patentNumber: 'WO-2026-019284-A2',
    date: '2026-07-20',
    noveltyScore: 79.4,
    status: 'Under Review',
    category: 'Cybersecurity',
    claimsCount: 12,
    priorArtMatches: 11,
  },
  {
    id: 'pat-005',
    title: 'Self-Healing Solid State Battery Electrolyte Formulation',
    patentNumber: 'US-2026-0041289-A1',
    date: '2026-07-18',
    noveltyScore: 91.0,
    status: 'Completed',
    category: 'Materials Science',
    claimsCount: 25,
    priorArtMatches: 4,
  },
  {
    id: 'pat-006',
    title: 'Transformer-Based Dynamic Video Compression Architecture',
    patentNumber: 'US-2026-0031842-A1',
    date: '2026-07-15',
    noveltyScore: 85.6,
    status: 'Completed',
    category: 'Artificial Intelligence',
    claimsCount: 16,
    priorArtMatches: 6,
  },
];

export const ACTIVITY_FEED_DATA = [
  {
    id: 'act-1',
    type: 'analysis_completed',
    title: 'Novelty Scan Completed',
    description: 'Quantum Micro-Fluidic Neural Processing Unit scored 94.8% novelty.',
    timestamp: '15 mins ago',
    iconName: 'CheckCircle2',
    iconColor: 'text-success',
  },
  {
    id: 'act-2',
    type: 'report_generated',
    title: 'Audit PDF Generated',
    description: 'Legal PDF report for US-2026-0084719-A1 compiled & downloaded.',
    timestamp: '2 hours ago',
    iconName: 'FileText',
    iconColor: 'text-primary-light',
  },
  {
    id: 'act-3',
    type: 'db_sync',
    title: 'USPTO Corpus Synced',
    description: 'Vector database refreshed with 42,000 new patent filings.',
    timestamp: '5 hours ago',
    iconName: 'RefreshCw',
    iconColor: 'text-secondary-light',
  },
  {
    id: 'act-4',
    type: 'ai_recommendation',
    title: 'Claim Amendment Suggested',
    description: 'AI model surfaced claim 3 rewriting suggestion to circumvent EP-3940192 prior art.',
    timestamp: '1 day ago',
    iconName: 'Lightbulb',
    iconColor: 'text-warning',
  },
  {
    id: 'act-5',
    type: 'patent_submitted',
    title: 'New Patent Draft Submitted',
    description: 'Draft "Biocompatible Graphene Glucose Sensor Array" uploaded for analysis.',
    timestamp: '2 days ago',
    iconName: 'UploadCloud',
    iconColor: 'text-primary-light',
  },
];

export const NOTIFICATIONS_DATA = [
  {
    id: 'notif-1',
    title: 'Analysis Completed',
    message: 'Your novelty report for US-2026-0098412-A1 is ready.',
    time: '10m ago',
    read: false,
    type: 'success',
  },
  {
    id: 'notif-2',
    title: 'New Report Available',
    message: 'Executive PDF audit summary generated for your team.',
    time: '2h ago',
    read: false,
    type: 'info',
  },
  {
    id: 'notif-3',
    title: 'Database Sync Complete',
    message: 'Global WIPO & EPO vector database updated successfully.',
    time: '6h ago',
    read: true,
    type: 'info',
  },
  {
    id: 'notif-4',
    title: 'Scheduled Maintenance',
    message: 'System upgrade scheduled for Sunday 02:00 UTC.',
    time: '1d ago',
    read: true,
    type: 'warning',
  },
];

export const QUICK_ACTIONS_DATA = [
  {
    id: 'action-new',
    title: 'Submit New Patent',
    description: 'Upload claims or paste abstract for vector scanning',
    iconName: 'PlusCircle',
    path: '/dashboard/new-analysis',
    color: 'from-blue-500/20 to-indigo-500/20',
    borderColor: 'border-primary/40',
  },
  {
    id: 'action-check',
    title: 'Run AI Novelty Check',
    description: 'Execute instant semantic comparison against prior art',
    iconName: 'Zap',
    path: '/dashboard/new-analysis',
    color: 'from-purple-500/20 to-pink-500/20',
    borderColor: 'border-secondary/40',
  },
  {
    id: 'action-report',
    title: 'Generate Audit Report',
    description: 'Compile legal PDF report with citations & score matrix',
    iconName: 'FileText',
    path: '/dashboard/reports',
    color: 'from-emerald-500/20 to-teal-500/20',
    borderColor: 'border-success/40',
  },
  {
    id: 'action-history',
    title: 'View History Archive',
    description: 'Browse, filter, and inspect past patent evaluations',
    iconName: 'History',
    path: '/dashboard/history',
    color: 'from-amber-500/20 to-orange-500/20',
    borderColor: 'border-warning/40',
  },
];
